### ISSUE TITLE
Add-on requesting to read browser history.

### ISSUE THREAD

**Issue by robbely** [basti564/DownQuest#14]
This auto-updated recently (to v1.5.0) and chrome disabled it and said there is a new permission I need to agree to "read your browser history".

I very much doubt browser history is needed for the add-on to function so please can you update with a version without this requirement.

**Comment by basti564** [comment]
You are correct. The message was from me requesting the `tabs` permission while testing to monitor for url changes on meta.com since the website isn't actually reloaded most of the time. Though this is unnecessary in the release since the extension already has host permission. I removed the permission in 11401f357c7a9f4eacad6935079e8399f333235c which is included in release [v1.5.1](https://github.com/basti564/DownQuest/releases/tag/v1.5.1). The Chrome and Edge extension stores both still need to accept this update as of now.
